### ISSUE TITLE
Incorrect GCD

### ISSUE THREAD

**Issue by shashi** [JuliaAlgebra/DynamicPolynomials.jl#104]
```julia
julia> using DynamicPolynomials

julia> @polyvar x y
(x, y)

julia> gcd((-x + 1) * (y^2+1), -x+1)
-xy² + y² - x + 1
```

Found via https://github.com/JuliaSymbolics/Symbolics.jl/issues/487

**Comment by blegat** [comment]
Should be fixed by https://github.com/JuliaAlgebra/DynamicPolynomials.jl/pull/105
