### ISSUE TITLE
Don't turn coefficients into float on div

### ISSUE THREAD

**Issue by shashi** [JuliaAlgebra/DynamicPolynomials.jl#144]
```julia
julia> pa = PolyForm(x+2y).p
2y + x

julia> pa/1
2.0y + x
```
It should at best be Rational... If one of the coeffs is already Float then it makes if the output has floats.

**Comment by blegat** [comment]
What is `PolyForm` ? I think it is consistent with Julia, `1 / 2` is also Float

**Comment by hersle** [comment]
Hi! `PolyForm` is a [wrapper in SymbolicUtils.jl](https://github.com/JuliaSymbolics/SymbolicUtils.jl/blob/master/src/polyform.jl), which underlies [Symbolics.jl](https://github.com/JuliaSymbolics/Symbolics.jl). Reliably working with integer/rational coefficients would greatly help symbolic calculations.

Anyway, here `div` is not consistent with base Julia:
```julia
julia> using DynamicPolynomials

julia> @polyvar x
(x,)

julia> div(x, x)
1.0

julia> div(7, 7)
1
```
Should/could this be fixed?

**Comment by shashi** [comment]
Thanks @hersle ! @blegat, we use `div`, `/` is just surface notation. `PolyForm` wraps your polynomials and implements the Symbolics expression interface.
