### ISSUE TITLE
wrong calculation with LexOrder?

### ISSUE THREAD

**Issue by KenZhenLin** [JuliaAlgebra/DynamicPolynomials.jl#155]
Hi,

Could you please help me understand this?

```julia
@polyvar toya[1:6] monomial_order = LexOrder
```
`@show toya[6]-(1+toya[1])` gives `toya[6] - (1 + toya[1]) = -toya₁`, the variable `toya[6]` and constant `-1` disappear,
while `@show toya[6]-1-toya[1]` is correct, and gives `(toya[6] - 1) - toya[1] = -1 + toya₆ - toya₁`

And `toya[6]-(1+toya[1]) == toya[6]-1-toya[1]` is `false`.

The above issue does NOT happen if I remove the `monomial_order = LexOrder`.

Thanks!

**Comment by blegat** [comment]
Are you using the latest version, it was fixed in https://github.com/JuliaAlgebra/DynamicPolynomials.jl/pull/153

**Comment by KenZhenLin** [comment]
> Are you using the latest version, it was fixed in #153

Oh ok,  sorry I'm not. I will try the latest and see if it works! Thanks a lot!
