### ISSUE TITLE
Undefined behavior for incomplete evaluations 

### ISSUE THREAD

**Issue by b-reinke** [JuliaAlgebra/DynamicPolynomials.jl#30]
It is possible to evaluate a polynomial with incomplete variable assignments, if the substitution uses simple enough types. See for example
```julia
julia> using DynamicPolynomials

julia> @polyvar x y
y

julia> f = x + y
x + y

julia> f(x=>1)
140545602820497 (or other garbage)
```

contrast to
```julia
julia> f(x=>BigInt(1))
ERROR: AssertionError: Variable y was not assigned a value
```

It seems to be a bug in

https://github.com/JuliaAlgebra/DynamicPolynomials.jl/blob/09bd7915f6dd1e6f4e98ba93d8d8b28ef5e4190e/src/subs.jl#L29-L37

as `Vector{Int}(undef, n)` and `isassigned` do not work together in the same way as for more complected types.

**Comment by blegat** [comment]
@b-reinke Yes, this is annoying, we found no way to add for a check for values such as `Int` without sacrificing performance in the evaluation. We would be interested if anyone has an idea :)
