### ISSUE TITLE
Rounding

### ISSUE THREAD

**Issue by PB12345** [JuliaAlgebra/DynamicPolynomials.jl#4]
Hi, would it be possible to include a function like this one:
```julia
import Base: round
function round(f::Polynomial{true,T}, s::Int) where {T<:Number}
    sum([round(coefficient(f[i]),s) * monomial(f[i]) for i in 1:length(f)])
end
```

(or maybe a more clever implementation that does this). Many thanks!

**Comment by blegat** [comment]
We could add something like this in MultivariatePolynomials:
```julia
Base.round(t::AbstractTermLike) = round(coefficient(t)) * monomial(t)
function Base.round(p::AbstractPolynomialLike)
    # round(0.1) is zero so we cannot use SortedUniqState
    polynomial(round.(terms(p)), SortedState())
end
```

**Comment by PB12345** [comment]
that would be great. I aim at computing polynomials numerically. Mostly they are integer polynomials and I get something like 1.00000001234 x^3. Would be really nice, if I could simply round that one. would very much appreciate if you could add that.

Cheers, Paul

**Comment by PB12345** [comment]
thank you! :)  could you also add an export command for it?

**Comment by blegat** [comment]
There is no need, `round` is already exported by Base.

**Comment by PB12345** [comment]
true. thank you. Could you add the option to round to a certain number of digits, though?

`Base.round(t::AbstractTermLike; s=1) = round(coefficient(t), s) * monomial(t)
function Base.round(p::AbstractPolynomialLike; s=1)
    # round(0.1) is zero so we cannot use SortedUniqState
    polynomial(round.(terms(p), s=1), SortedState())
end`

**Comment by blegat** [comment]
Superseeded by https://github.com/JuliaAlgebra/MultivariatePolynomials.jl/issues/65
