### ISSUE TITLE
Nice display of Vectors of polynomials

### ISSUE THREAD

**Issue by PB12345** [JuliaAlgebra/DynamicPolynomials.jl#5]
Hi,

I am working with vectors of polynomials and they tend to have a lot of variables. When I print those to the console it's not clear where one polynomial stops and the next begins, because Julia prints elements of vectors without line break in between them. Would you be willing to include a function like the following?

function niceshow(P::Vector{AbstractPolynomialLike}) 
    for p in P
        println("$p \n")
    end
end

**Comment by blegat** [comment]
Normally, `show` and `print` should give a short output, you can use `display` to have what you want
```julia
julia> using DynamicPolynomials

julia> @polyvar x
x

julia> y = [x^2 + 1, x+1]
2-element Array{DynamicPolynomials.Polynomial{true,Int64},1}:
 x^2 + 1
 x + 1  

julia> display(y)
2-element Array{DynamicPolynomials.Polynomial{true,Int64},1}:
 x^2 + 1
 x + 1  

julia> show(y)
DynamicPolynomials.Polynomial{true,Int64}[x^2 + 1, x + 1]
julia> print(y)
DynamicPolynomials.Polynomial{true,Int64}[x^2 + 1, x + 1]
```

**Comment by PB12345** [comment]
true. thank you for your quick answer!
