### ISSUE TITLE
Variables get lost in Substitution 

### ISSUE THREAD

**Issue by manuelbb-upb** [JuliaAlgebra/DynamicPolynomials.jl#92]
Hi, 
I noticed something strange:
When there are variables with a zero coefficient and one performs substitution, these variables get lost.

MWE:
```julia
using DynamicPolynomials
@polyvar x[1:2]
p = 1 * x[1] + 0 * x[2]
variables(p) == x

P = subs(p, x => x)
variables(P) == x[1]    # x[2] gets lost
```
My current dumb workaround is to add `sum(0*x)` after substitution to "restore" the variable information.

**Comment by votroto** [comment]
Ouch, I guess it's in the spirit of "dynamicity", but I didn't expect this:
```julia
@polyvar x y
p = x + y
subs(p, x => 1) |> variables # returns [x, y]
```
I expected `[y]`. Is there a workaround?

**Comment by blegat** [comment]
You can use `effective_variables`

**Comment by votroto** [comment]
Good point, sorry for being cryptic.
My current issue is that e.g. SumOfSquares.jl uses MultivariatePolynomials.jl and this commit breaks it slightly, as it uses all `variables`. 
Let's say I want to optimize a polynomial after making substitutions; How can I force the "expected" variables for the polynomial?

**Comment by blegat** [comment]
Good point, SumOfSquares should probably use `effective_variables`. Could you open an issue in SumOfSquares ? You would have the same issue with `variables(x^2 + y^2 - y^2)` being `[x, y]` so I think this change with substitution is consistent.

**Comment by blegat** [comment]
Yes, the order is guaranteed;
